### ISSUE TITLE
Python documentation

### ISSUE THREAD

**Issue by qiaofeng1227** [Websoft9/ansible-python#1]
Solution charpter
1. Install/upgrade Django, Django cli
2. virtualenvwrapper cmd

**Comment by morning-tan** [comment]
Document (EN) 请优先补充。特别是安装部署章节。以便产品在AWS平台上架审核。

**Comment by chendelin1982** [comment]
剩余：framework-django， solution-addapps， solution-arch 未翻译

**Comment by chendelin1982** [comment]
done
