### ISSUE TITLE
Install python3.8 and pip3.8 on AmazonLinux2

### ISSUE THREAD

**Issue by tqf6** [Websoft9/ansible-python#11]
**Describe the bug**

## Deployment method

- [ ] subscription image from MarketPlace of Cloud
- [ ] All-in-one Installer
- [ ] ansible-playbook cli
- [x] mcloud
- [ ] create instance from private image

## Bug source

- [ ] Bugs from installation 
- [x] Bugs from first use
- [ ] Other (You should describe it)   

## System Environment

**Application Version**

e.g v4.5

**OS**

- [ ] Ubuntu18.x
- [ ] Ubuntu20.x
- [ ] CentOS7.x
- [ ] CentOS8.x
- [x] AmazonLinux2
- [ ] OracleLinux7.8
- [ ] OracleLinux8.2
- [ ] Other (You should describe it) 

**Cloud PlatForm**

- [ ] Azure
- [x] Aws
- [ ] 阿里云
- [ ] 腾讯云
- [ ] 华为云
- [ ] AlibabaCloud
- [ ] HUWEICloud
- [ ] Other (You should describe it) 

### Bug Context

Bug context includes bug error, error logs and service status, it is very important for resolving issue

```
# bug error
(paste here) 

# service status 
54.160.83.235

# error logs
(paste here) 
```

### Bug Screenshot

![image](https://user-images.githubusercontent.com/83911329/123590236-f79ede80-d81c-11eb-944e-3cde02efeea6.png)

## Your suggestion

**The reason of Bug**

You can describe the reason if you have found it

**Your solution for Bug**

You can describe your solution here

**Additional context**

You can add any other context about the problem here.

**Comment by QiuJiaHon** [comment]
![image](https://user-images.githubusercontent.com/95324527/147517769-8b3042ec-89af-4ddd-9538-4f2817b626bd.png)

**Comment by QiuJiaHon** [comment]
![image](https://user-images.githubusercontent.com/95324527/147543468-1fa2866a-d1f6-4f66-9f0a-f0d55bf46a7a.png)

**Comment by morning-tan** [comment]
![RUZN46TYP6K8@W9PZ5T`UQ6](https://user-images.githubusercontent.com/54173243/156139782-74d43b90-1b4d-4b8e-881d-ad3652c67306.png)

**Comment by chendelin1982** [comment]
use docker image
