### ISSUE TITLE
Add mongodb5.0(optional)

### ISSUE THREAD

**Issue by qiaofeng1227** [Websoft9/ansible-python#12]
1. mongodb 5.0 released, add to latest Python runtime

**Comment by hnczhjh** [comment]
![image](https://user-images.githubusercontent.com/86603933/130884296-4f3383a6-c921-4fd0-b833-799c52d42190.png)

![image](https://user-images.githubusercontent.com/86603933/130884548-afb78b49-a1a3-4cb5-a74f-7c6789676a02.png)
