### ISSUE TITLE
mongodb initialization failed

### ISSUE THREAD

**Issue by natk9** [Websoft9/ansible-python#13]
mongodb密码初始化失败，还是默认密码

![image](https://user-images.githubusercontent.com/40535348/131104861-2c3dc342-30e1-4fab-8ff2-080e2b1bb9c3.png)

**Comment by qiaofeng1227** [comment]
this is small bug

**Comment by hnczhjh** [comment]
#### mongodb passwd init and adminmongo add success
![image](https://user-images.githubusercontent.com/86603933/131111577-6046b897-efc6-4a90-a9bf-e8f63cd577bb.png)

**Comment by chenyujie0116** [comment]
python3.8 with mysql8.0,mongodb5.0 on Azure on ubuntu20.04,role_docker add repository failed.
docker on ubuntu20.04 on Azure,role_docker add repository successed.



![TN3UW 1 24S()M{0X~C4N8P](https://user-images.githubusercontent.com/44333047/132644719-2c43d613-7e4c-4212-aede-a7e6fabec4e6.png)
