### ISSUE TITLE
can't run django on CentOS7.9

### ISSUE THREAD

**Issue by tqf6** [Websoft9/ansible-python#3]
**Describe the bug**

## Deployment method

- [ ] subscription image from MarketPlace of Cloud
- [ ] All-in-one Installer
- [ ] ansible-playbook cli
- [x] mcloud
- [ ] create instance from private image

## Bug source

- [x] Bugs from installation 
- [ ] Bugs from first use
- [ ] Other (You should describe it)   

## System Environment

**Application Version**

e.g v4.5

**OS**

- [ ] Ubuntu18.x
- [ ] Ubuntu20.x
- [x] CentOS7.x
- [ ] CentOS8.x
- [ ] AmazonLinux2
- [ ] OracleLinux7.8
- [ ] OracleLinux8.2
- [ ] Other (You should describe it) 

**Cloud PlatForm**

- [x] Azure
- [ ] Aws
- [ ] 阿里云
- [ ] 腾讯云
- [ ] 华为云
- [ ] AlibabaCloud
- [ ] HUWEICloud
- [ ] Other (You should describe it) 

### Bug Context

Bug context includes bug error, error logs and service status, it is very important for resolving issue

```
# bug error
(paste here) 

# service status 
(paste here) 

# error logs
(paste here) 
```

### Bug Screenshot
![image](https://user-images.githubusercontent.com/83911329/120284050-6d7f5b00-c2ee-11eb-9471-264f1093c4c5.png)

## Your suggestion

**The reason of Bug**

You can describe the reason if you have found it

**Your solution for Bug**

You can describe your solution here

**Additional context**

You can add any other context about the problem here.

**Comment by zengxc-1996** [comment]
```
The reason is a lack of library files

Use yum install python3-devel to solve the problem
```

**Comment by zengxc-1996** [comment]
tested on azure centos 7.x OK:

```
ok: [168.61.144.128] => {
    "end_check_versions.stdout_lines": [
        "nginx version: nginx/1.20.1",
        "python3 version: Python 3.8.6",
        "pip version: pip 19.3.1 from /opt/rh/rh-python38/root/usr/lib/python3.8/site-packages/pip (python 3.8)",
        "django version: 3.2.4",
        "mysql  Ver 14.14 Distrib 5.7.34, for Linux (x86_64) using  EditLine wrapper",
        "Docker version 20.10.7, build f0df350",
        "phpmyadmin version: \"version\": \"5.1.1\",",
        "System version: CentOS 7.9"
    ]
}
