### ISSUE TITLE
python3.6 

### ISSUE THREAD

**Issue by tqf6** [Websoft9/ansible-python#4]
**Describe the bug**

## Deployment method

- [ ] subscription image from MarketPlace of Cloud
- [ ] All-in-one Installer
- [ ] ansible-playbook cli
- [x] mcloud
- [ ] create instance from private image

## Bug source

- [x] Bugs from installation 
- [ ] Bugs from first use
- [ ] Other (You should describe it)   

## System Environment

**Application Version**

e.g v4.5

**OS**

- [ ] Ubuntu18.x
- [ ] Ubuntu20.x
- [x] CentOS7.x
- [ ] CentOS8.x
- [ ] AmazonLinux2
- [ ] OracleLinux7.8
- [ ] OracleLinux8.2
- [ ] Other (You should describe it) 

**Cloud PlatForm**

- [ ] Azure
- [ ] Aws
- [x] 阿里云
- [x] 腾讯云
- [ ] 华为云
- [ ] AlibabaCloud
- [ ] HUWEICloud
- [ ] Other (You should describe it) 

### Bug Context

Bug context includes bug error, error logs and service status, it is very important for resolving issue

```
# bug error
(paste here) 

# service status 
(paste here) 

# error logs
(paste here) 
```

### Bug Screenshot

![image](https://user-images.githubusercontent.com/83911329/122007212-49417500-cdea-11eb-8a26-f9f11351d719.png)

## Your suggestion

**The reason of Bug**

You can describe the reason if you have found it

**Your solution for Bug**

You can describe your solution here

**Additional context**

You can add any other context about the problem here.

**Comment by zengxc-1996** [comment]
tested python3.6 on aliyun ubuntu20.04 :  no package

only python3.8 python3.9

![image](https://user-images.githubusercontent.com/63622990/122154980-a3990f00-ce98-11eb-8d69-8e4ccdba17d8.png)

**Comment by zengxc-1996** [comment]
tested python3.6 on azure ubuntu 20.04:  no package
```
fatal: [40.77.102.99]: FAILED! => {"changed": false, "msg": "No package matching 'python3.6' is available"}
```

only python3.8 and python3.9

![image](https://user-images.githubusercontent.com/63622990/122153123-e6f17e80-ce94-11eb-9625-c15dff888469.png)

**Comment by zengxc-1996** [comment]
tested python3.6 on azure centos7.x :  is ok

only python34 python36 rh-python35 rh-python36 rh-python38 

```
[websoft9@pythonzengxc-CentOS7 ~]$ python3
Python 3.6.8 (default, Nov 16 2020, 16:55:22) 
[GCC 4.8.5 20150623 (Red Hat 4.8.5-44)] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> 
```

**Comment by zengxc-1996** [comment]
tested python3.6 on aliyun centos7.x :  

only  python34 python36 ry-python35 rh-python36 rh-python38

```
[root@iZj6ceo2x0nf42ug6oyzpxZ ~]# python3
Python 3.6.8 (default, Nov 16 2020, 16:55:22) 
[GCC 4.8.5 20150623 (Red Hat 4.8.5-44)] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> 

    "end_check_versions.stdout_lines": [
        "nginx version: nginx/1.20.1",
        "sqlite3 version: 3.35.5",
        "python3 version: Python 3.6.8",
        "pip version: pip 21.1.2 from /usr/local/lib/python3.6/site-packages/pip (python 3.6)",
        "django version: 3.2.4",
        "mysql  Ver 14.14 Distrib 5.7.34, for Linux (x86_64) using  EditLine wrapper",
        "Docker version 20.10.7, build f0df350",
        "phpmyadmin version: \"version\": \"5.1.1\",",
        "System version: CentOS 7.9",
        "Image name: pythonzengxc-CentOS7.9"

```

**Comment by zengxc-1996** [comment]
tested python3.6 on aws linux2 :  error

only  python34 python36

![image](https://user-images.githubusercontent.com/63622990/122174460-55decf80-ceb5-11eb-96e7-0aeb55821c08.png)

![image](https://user-images.githubusercontent.com/63622990/122174507-5d05dd80-ceb5-11eb-9e89-8ee8bcf0e0e5.png)

no python3.6 cli ,default version is python3.7
```
Loaded plugins: extras_suggestions, langpacks, priorities, update-motd
Package matching python3-3.6.8-18.el7.x86_64 already installed. Checking for update.
Nothing to do
[root@ip-172-31-47-160 ec2-user]# 
```

**Comment by zengxc-1996** [comment]
tested python3.6 on aws ubuntu18 :   is ok

only  python3.6 python3.7 python3.8

![image](https://user-images.githubusercontent.com/63622990/122178251-fedaf980-ceb8-11eb-8c1b-3af4a432a0ef.png)

**Comment by zengxc-1996** [comment]
tested python3.6 on aws ubuntu20 :  no package

only python38 python39

![image](https://user-images.githubusercontent.com/63622990/122183180-92162e00-cebd-11eb-9a18-c5bf1ebe5551.png)
