### ISSUE TITLE
Install pymongo for Ansible MongoDB module

### ISSUE THREAD

**Issue by tqf6** [Websoft9/ansible-python#9]
**Describe the bug**

## Deployment method

- [ ] subscription image from MarketPlace of Cloud
- [ ] All-in-one Installer
- [ ] ansible-playbook cli
- [x] mcloud
- [ ] create instance from private image

## Bug source

- [x] Bugs from installation 
- [ ] Bugs from first use
- [ ] Other (You should describe it)   

## System Environment

**Application Version**

e.g v4.5

**OS**

- [ ] Ubuntu18.x
- [x] Ubuntu20.x
- [x] CentOS7.x
- [ ] CentOS8.x
- [ ] AmazonLinux2
- [ ] OracleLinux7.8
- [ ] OracleLinux8.2
- [ ] Other (You should describe it) 

**Cloud PlatForm**

- [x] Azure
- [x] Aws
- [x] 阿里云
- [ ] 腾讯云
- [ ] 华为云
- [ ] AlibabaCloud
- [ ] HUWEICloud
- [ ] Other (You should describe it) 

### Bug Context

Bug context includes bug error, error logs and service status, it is very important for resolving issue

```
# bug error
(paste here) 

# service status 
47.243.194.85 

# error logs
(paste here) 
```

### Bug Screenshot

![image](https://user-images.githubusercontent.com/83911329/123222932-00cd3a00-d503-11eb-9cd3-0b864c1f350e.png)

## Your suggestion

**The reason of Bug**

You can describe the reason if you have found it

**Your solution for Bug**

You can describe your solution here

**Additional context**

You can add any other context about the problem here.

**Comment by qiaofeng1227** [comment]
```
[root@iZbp10rgkmt4l5nxhzulkxZ ~]# python3 --version
Python 3.8.6
[root@iZbp10rgkmt4l5nxhzulkxZ ~]# pip -V
pip 21.1.2 from /opt/rh/rh-python38/root/usr/local/lib/python3.8/site-packages/pip (python 3.8)
[root@iZbp10rgkmt4l5nxhzulkxZ ~]# pip install pymongo
Looking in indexes: http://mirrors.cloud.aliyuncs.com/pypi/simple/
Collecting pymongo
  Downloading http://mirrors.cloud.aliyuncs.com/pypi/packages/87/17/b15596bc492ca608c41ad54b718f83e6840da46f71fab4f14eb4d2572de7/pymongo-3.11.4-cp38-cp38-manylinux2014_x86_64.whl (531 kB)
     |████████████████████████████████| 531 kB 24.3 MB/s 
Installing collected packages: pymongo
Successfully installed pymongo-3.11.4
WARNING: Running pip as root will break packages and permissions. You should install packages reliably by using venv: https://pip.pypa.io/warnings/venv
[root@iZbp10rgkmt4l5nxhzulkxZ ~]# pip2 -V
pip 20.3.4 from /usr/lib/python2.7/site-packages/pip (python 2.7)
[root@iZbp10rgkmt4l5nxhzulkxZ ~]# pip2 install pymongo
DEPRECATION: Python 2.7 reached the end of its life on January 1st, 2020. Please upgrade your Python as Python 2.7 is no longer maintained. pip 21.0 will drop support for Python 2.7 in January 2021. More details about Python 2 support in pip can be found at https://pip.pypa.io/en/latest/development/release-process/#python-2-support pip 21.0 will remove support for this functionality.
Looking in indexes: http://mirrors.cloud.aliyuncs.com/pypi/simple/
Collecting pymongo
  Downloading http://mirrors.cloud.aliyuncs.com/pypi/packages/1a/67/62f25bcaac57b67489c42880e458883559f171cbb32dc5ed5effcddc154e/pymongo-3.11.4-cp27-cp27mu-manylinux1_x86_64.whl (488 kB)
     |████████████████████████████████| 488 kB 25.9 MB/s 
Installing collected packages: pymongo
Successfully installed pymongo-3.11.4


```

**Comment by geraintlyu** [comment]
阿里云centos7.9 -> OK
阿里云ubuntu20.04 -> OK
azure-ubuntu20.04 -> ok

**Comment by geraintlyu** [comment]
azure-centos7.9

![wrong](https://user-images.githubusercontent.com/53968450/123410249-aeaf1600-d5e1-11eb-9814-4d375c12d92b.png)

**Comment by tqf6** [comment]
aws-linux
54.160.83.235
![image](https://user-images.githubusercontent.com/83911329/123590538-582e1b80-d81d-11eb-805d-c3a408d8471d.png)
